### ISSUE TITLE
Add indicator that process is still running

### ISSUE THREAD

**Issue by kdheepak** [singularitti/vscode-julia-formatter#1]
Sometimes it takes a while to run JuliaFormatter.jl and sometimes there are no changes to a file, and it can be hard to tell which state the file is in. If edits to a file while JuliaFormatter.jl is still running causes issues. This can be resolved by adding a status bar icon temporarily to indicate that the process is still running.

**Comment by singularitti** [comment]
How about [this commit](https://github.com/singularitti/vscode-julia-formatter/commit/0a710da38ba1f189e81a8a5e84daa3b198b32fc9)? Could you try it?

**Comment by kdheepak** [comment]
Works great!!! Thanks for the quick feature additions!
