### ISSUE TITLE
"alwaysForIn" not working

### ISSUE THREAD

**Issue by msekino** [singularitti/vscode-julia-formatter#14]
Thank you for the very useful extension!

I set `"juliaFormatter.alwaysForIn": true` however,  
> for i in 1:N

was transformed to
> for i = 1:N

VSCode Version: 1.47.0
OS: Windows 10
Julia Formatter Version: 0.2.1

**Comment by singularitti** [comment]
I think that's because I set `alwaysForIn = true` in my code, while `JuliaFormatter.jl` defaults to `false`.

**Comment by singularitti** [comment]
Fixed in the new version.
