### ISSUE TITLE
Error "The content of the file is newer."

### ISSUE THREAD

**Issue by samuela** [singularitti/vscode-julia-formatter#15]
I'm getting an error after I attempt to save twice with "Format on Save" enabled:
```
Failed to save 'train.jl': The content of the file is newer. Please compare your version with the file contents or overwrite the content of the file with your changes.
```

I think this may be related to https://github.com/singularitti/vscode-julia-formatter/issues/12 but I'm not sure.

Extension version: v0.2.1

Version: 1.48.0-insider
Commit: 8c426f9f3b6b18935cc6c2ec8aa6d45ccd88021e
Date: 2020-07-23T05:40:23.559Z
Electron: 9.1.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.4.0

**Comment by samuela** [comment]
```
  "[julia]": {
    "editor.defaultFormatter": "singularitti.vscode-julia-formatter",
    // See https://github.com/singularitti/vscode-julia-formatter/issues/15.
    "files.saveConflictResolution": "overwriteFileOnDisk"
  }
```
This gets rid of the error message but the file as shown in the editor is still incorrect, doesn't show formatter changes.

**Comment by singularitti** [comment]
Hi, can you try version 0.3.0 & see if it is fixed for you?
