### ISSUE TITLE
"Format Document" has no effect when file is unsaved

### ISSUE THREAD

**Issue by samuela** [singularitti/vscode-julia-formatter#16]
Just as the title says. I've found that "Format Document" only does anything when the file has no unsaved changes.

Extension version: v0.2.1

Version: 1.48.0-insider
Commit: 8c426f9f3b6b18935cc6c2ec8aa6d45ccd88021e
Date: 2020-07-23T05:40:23.559Z
Electron: 9.1.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.4.0

**Comment by singularitti** [comment]
Hi, can you try version 0.3.0 & see if it is fixed for you?

**Comment by samuela** [comment]
just updated to 0.3.0. i'll check back in if i come across the issue again!
