### ISSUE TITLE
`expanduser` on `executablePath` setting

### ISSUE THREAD

**Issue by kdheepak** [singularitti/vscode-julia-formatter#2]
Would you be open to adding the following code?

```javascript
const os = require('os');
const homeDirectory = os.homedir();
function resolveHome(pathWithTilde: string): string {
	return homeDirectory ? pathWithTilde.replace(/^~(?=$|\/|\\)/, homeDirectory) : pathWithTilde;
};
```

and adding a call to `resolveHome` to the following line?

https://github.com/singularitti/vscode-julia-formatter/blob/8cd60547a49b7c5fab20827353ab3b8e1de059fb/src/extension.ts#L14

Currently, if I use `~/Applications/Julia-1.3.app/Contents/Resources/julia/bin/julia`, I get an error with this plugin since it does not expand the `~`.

The above code is from [`untildify`](https://github.com/sindresorhus/untildify/blob/f85a087418aeaa2beb56fe2684fe3b64fc8c588d/index.js) which is used in [`vscode-python`](https://github.com/microsoft/vscode-python/blob/a8bd87e9f9f74773badc33f9d9f8cd0c01072ca5/src/client/common/platform/pathUtils.ts#L6) for similar purposes.

Alternatively, you can add the `untildify` package as a dependency.

**Comment by singularitti** [comment]
Sorry, I just see it today. Will [it work](https://github.com/singularitti/vscode-julia-formatter/commit/0a310ba7b9e46ab39268de2bc1222503366aa236) now?

**Comment by kdheepak** [comment]
I tested the latest master and it works great!
