### ISSUE TITLE
"Unknown Error: Could not format file. Full error: Exit with error code: 1"

### ISSUE THREAD

**Issue by samuela** [singularitti/vscode-julia-formatter#23]
I'm running in SSH remote mode, and I just installed the extension and reloaded the window. I'm getting this error whenever I try to format:
```
### in Log (Remote Extension Host)
[2020-09-12 00:10:26.683] [exthost] [error] [singularitti.vscode-julia-formatter] provider FAILED
[2020-09-12 00:10:26.683] [exthost] [error] Error: Exit with error code: 1
	at ChildProcess.<anonymous> (/home/samuela/.vscode-server-insiders/extensions/singularitti.vscode-julia-formatter-0.3.0/node_modules/@rauschma/stringio/dist/src/index.js:164:24)
	at Object.onceWrapper (events.js:313:26)
	at ChildProcess.emit (events.js:223:5)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
```

**Comment by samuela** [comment]
Relevant line seems to be `reject(new Error('Exit with error code: ' + code));` in

```js
function onExit(childProcess) {
    return new Promise((resolve, reject) => {
        childProcess.once('exit', (code, signal) => {
            if (code === 0) {
                resolve(undefined);
            }
            else {
                reject(new Error('Exit with error code: ' + code));
            }
        });
        childProcess.once('error', (err) => {
            reject(err);
        });
    });
}
```

**Comment by singularitti** [comment]
Not sure what's going on. @kmsquire is there any chance you could have a look at it?

**Comment by kmsquire** [comment]
Basically, this is equivalent to a try-catch on running the Julia subprocess, and all it's saying is that the formatting failed, without giving an informative reason why.

This is actually related to my comment [here](https://github.com/singularitti/vscode-julia-formatter/pull/19#issuecomment-690754458).  I want to return the error message from Julia, but when I was working on this, I couldn't find a way to do this reliably.  It's captured as part of the stderr output, but there didn't seem to be a nice way to get that information passed back.

That said, I'm glad you posted the `onExit` code above.  That's from a package I was using to make things nicer, but it looks like we can just reimplement that function and have it grab stderr when things fail.  I'll try that and post back here.

**Comment by kmsquire** [comment]
Okay, I've opened #24, which collects the Julia error message and returns it as part of the error to VSCode.  It isn't formatted very nicely (I don't have any control over that), but at least it gives something back that might aid in debugging.

In the mean time, @samuela, if you want to test it out before it's merged and a new release is made, you can download and install the vsix file from [here](https://drive.google.com/file/d/1kBgicGLhHw6P7pmZdMLDfmupfYuSaL65/view?usp=sharing).  Hopefully this version will give enough information to debug.

[Here](https://github.com/eamodio/vscode-gitlens/wiki/Installing-Prereleases-(vsix)) are some instructions on how to install the extension after downloading.

**Comment by bbejanov** [comment]
I have the same problem. I can test the fix, but I can't download from google drive. Where can I find instructions on how to create the vsix file from source?

**Comment by bbejanov** [comment]
Never mind, I don't have the problem anymore. 

I installed the JuliaFormatter package in the root Julia environment on the remote server and the problem disappeared.
