### ISSUE TITLE
Does this still pickup the `.JuliaFormatter.toml` files?

### ISSUE THREAD

**Issue by jlperla** [singularitti/vscode-julia-formatter#27]
I am having a lot of trouble in the last few week with this extension and old toml files that used to work?

**Comment by singularitti** [comment]
I guess because we switch from [`format`](https://domluna.github.io/JuliaFormatter.jl/stable/api/#JuliaFormatter.format-Tuple{Any}) to [`format_text`](https://domluna.github.io/JuliaFormatter.jl/stable/api/#JuliaFormatter.format_text-Tuple{AbstractString}). This feature is currently no available. Maybe we need a new design to cover this.

**Comment by jlperla** [comment]
@singularitti   Sorry to bump this, but has there been any progress on a solution (or are you planning something else like an eventual merge into the main vscode extension).  This has been the killer feature for me recommending JuliaFormatter, and downgrading a vscode extension isn't feasible in the medium-run.

**Comment by singularitti** [comment]
@jlperla Yeah I know it. I am sorry no progress was made but I can release a new version like 0.3.1 that is actually 0.2.2 anyway for the time being.

**Comment by jlperla** [comment]
Hi there, I wanted to check if the `JuliaFormatter.toml` file is supposed to be working now with the latest released versions?

**Comment by tmadeira** [comment]
Is there any workaround to make it use .JuliaFormatter.toml configuration at the moment? I've just installed v0.6.3 and it's still not using it.

**Comment by singularitti** [comment]
Hey guys @jlperla @tmadeira, the latest (1.5.0+) julia-vscode plugin already supports JuliaFormatter.jl as its default formatter. Could you try that?

**Comment by jlperla** [comment]
Seems to work great as far as I can tell!  I think this extension can be deprecated soon enough.
