### ISSUE TITLE
Formatter breaks code

### ISSUE THREAD

**Issue by rssdev10** [singularitti/vscode-julia-formatter#28]
```
JuliaFormatter v0.10.9
julia> versioninfo()
Julia Version 1.5.3
Commit 788b2c77c1 (2020-11-09 13:37 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  CPU: Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, broadwell)
Environment:
  JULIA_EDITOR = "/Applications/Visual Studio Code.app/Contents/Resources/app/bin/code"
  JULIA_NUM_THREADS = 
```

Following code fragment from the attached file:
```julia
p = plot([sin, cos], zeros(0),
          leg = false,
          xlims = (0, 2π),
          ylims = (-1, 1))
anim = Animation()
for x = range(0, stop = 2π, length = 20)
    push!(p, x, Float64[sin(x), cos(x)])
    frame(anim)
end
gif(anim, "out/sin_cos_anim.gif", fps = 15)
```

is completely broken after applying the formatter from VS Code 
```julia
p = plot([sin, cos], zeros(0), leg = false, xlims = (0, 2π), ylims = (-1, 1))
anim = Animation()
for x in range(0, stop = 2π, length = 20)
    push!(p, x, Float64[sin(x), cos(x)])
    frame(anim)
end
gif(anim, "out/sin_cos_anim.gif", fps = 15)
    push!(p, x, Float64[sin(x), cos(x)])
    frame(anim)
end
gif(anim, "out/sin_cos_anim.gif", fps = 15)
```

[formatter.txt](https://github.com/singularitti/vscode-julia-formatter/files/5630354/formatter.txt)

**Comment by casabre** [comment]
I am observing the same within VS Code too. Additionally it takes ages until the formatting has finished in a broken file. Sometimes, the formatting stops with an error message pop-up.

**Comment by singularitti** [comment]
I am aware of this bug, but I am currently occupied and have no time to fix it. Sorry for now!

**Comment by casabre** [comment]
> I am aware of this bug, but I am currently occupied and have no time to fix it. Sorry for now!

@singularitti I know that it was working. Do you maybe know the version to downgrade for the moment?

**Comment by singularitti** [comment]
> > I am aware of this bug, but I am currently occupied and have no time to fix it. Sorry for now!
> 
> @singularitti I know that it was working. Do you maybe know the version to downgrade for the moment?

0.2.2. I believe the bug was introduced in https://github.com/singularitti/vscode-julia-formatter/pull/24

**Comment by FuZhiyu** [comment]
I have a similar issue not sure whether it's caused by the same bug, but let me report it here:

```julia
function solve_policies!(𝔸, cmat, lmat, smat, umat, V::AbstractArray{D,2}, param; V̇=nothing)
    @unpack 𝔸, cmat, lmat, smat = cache
    w, r = @unpack S
    for iter in CartesianIndices(V)
        nothing
    end
end


function policyfunction(Vbb::D, Vbf, r, w, b, param)
    if validF & (!validB | (Hcf >= Hcb)) 
        c = cf
    elseif validB & (!validF | (Hcb >= Hcf))# & (Hcb >= Hc0)
        c = cb
    else
        c0, l0, s0, u0, Hc0 = solveclSS(r, w, b, param)
    end
    return c, l, s, u
end
```
will be
```julia
function solve_policies!(
    𝔸,
    cmat,
    lmat,
    smat,
    umat,
    V::AbstractArray{D,2},
    param;
    V̇ = nothing,
)
    @unpack 𝔸, cmat, lmat, smat = cache
    w, r = @unpack S
    for iter in CartesianIndices(V)
        nothing
    end
end


function policyfunction(Vbb::D, Vbf, r, w, b, param)
    if validF & (!validB | (Hcf >= Hcb)) 
        c = cf
    elseif validB & (!validF | (Hcb >= Hcf))# & (Hcb >= Hc0)
        c = cb
    else
end


function policyfunction(Vbb::D, Vbf, r, w, b, param)
    if validF & (!validB | (Hcf >= Hcb))
        c = cf
    elseif validB & (!validF | (Hcb >= Hcf))# & (Hcb >= Hc0)
        c = cb
    else
```

**Comment by rben01** [comment]
I cloned locally and tinkered. Seems like it's sufficient to replace the entire `format_stdin()` function inside the template string in the `return` statement of`buildFormatArgs()` with just this :

```Julia
function format_stdin()
    print(format_text(String(read(stdin)); ${options}))      
end
```

The current version does some funky reading of `stdin` with `readavailable` instead of just reading the whole thing in one go with `read`.

**Comment by rben01** [comment]
Just submitted a PR that I think fixes this.

https://github.com/singularitti/vscode-julia-formatter/pull/40

**Comment by singularitti** [comment]
Hey gus, @rssdev10, @casabre, @FuZhiyu, can you try v0.5.1 see if it solves your problems?

**Comment by rssdev10** [comment]
Thanks, for the code from my primary message it works good.

**Comment by FuZhiyu** [comment]
It also works for my case now. Thanks!

**Comment by jessymilare** [comment]
I was also having this problem and v0.5.1 seems to work fine.
