### ISSUE TITLE
could not 

### ISSUE THREAD

**Issue by TY-Cheng** [singularitti/vscode-julia-formatter#29]
VS Code 1.51.1, mac 10.13.6, Unknown Error: Could not format file. Full error: Exit with error code: 1
tried to install the ']add JuliaFormatter' via the terminal... and added the extension via 
![image](https://user-images.githubusercontent.com/14033617/101734951-109fa680-3afc-11eb-9a25-66aaf375044b.png)

**Comment by singularitti** [comment]
> VS Code 1.51.1, mac 10.13.6, Unknown Error: Could not format file. Full error: Exit with error code: 1
> tried to install the ']add JuliaFormatter' via the terminal... and added the extension via
> ![image](https://user-images.githubusercontent.com/14033617/101734951-109fa680-3afc-11eb-9a25-66aaf375044b.png)

I guess it's because you have the `if (true) {...}` statement there. It's not Julia. `JuliaFormatter.jl` only works for valid Julia syntax.
