### ISSUE TITLE
Formatting an unsaved file may cause loss of data

### ISSUE THREAD

**Issue by norru** [singularitti/vscode-julia-formatter#5]
Formatting an unsaved file produces highly dangerous outcomes:

- the file on disk is overwritten with the formatted "*last saved edit**
- the current unsaved buffer (containing potentially critical edits) is unchanged and as such **out of sync with its persisted version**
- attempting to save the file causes a "Failed to save" error message 

File should only be written to disk **if and when the user decides to do so**. 

The plugin should either:

- format the buffer in memory so the user can undo the formatting. User can decide to keep the formatting changes by saving explicitly.
- format the buffer on disk but *disallow the formatting of an unsaved file* - this could cause data loss if the user does not accept the formatter's results so it should be preceded by a confirmation message.

To reproduce:

- load an existing document from file
- make some "unformats" to the file (ie unindent a few indented expressions)
- save the document
- do some (potentially critical) edits
- Format with/JuliaFormatter
- Wait some time (the plugin is very slow), until the "Formatting..." message disappears from the status bar
- the current document is unchanged
- try to save the current document

Results:
- File cannot be saved, Notification alert will show "Failed to save..."
- The file on disk has been formatted

Expected results:
- formatting is immediate
- current document (in memory) is formatted
- local file is unchanged
- current document can be saved on the local file

**Comment by singularitti** [comment]
Hi, can you try version 0.3.0 & see if it is fixed for you?
