### ISSUE TITLE
Another error with Meta.parseall?

### ISSUE THREAD

**Issue by pgbarletta** [singularitti/vscode-julia-formatter#50]
I got `ERROR: UndefVarError: parseall not defined` from the extension when I tried to format a simple document:
```
struct Result
    profile::Any
    score::Any
end
```
When I came to the repo I saw the last commmit is related to this issue.

Thanks for any help.

**Comment by singularitti** [comment]
Hi @pgbarletta, I have no trouble formatting this text. What is your [minimal working example](https://en.wikipedia.org/wiki/Minimal_working_example)?

**Comment by pgbarletta** [comment]
Well, it's just that: [MWE](https://gist.github.com/pgbarletta/6cd0d316b0dfac5036bff123f4b5220f)
And I get:
```
Initialized Julia Formatter extension
Running Julia with args: ["--compile=min","-e","using JuliaFormatter\n\n        function throw_if_parse_err(ex)\n            ex.head !== :toplevel && return\n            for (i, arg) in pairs(ex.args)\n                !(arg isa Expr && (arg.head === :error || arg.head === :incomplete)) && continue\n                line_node = ex.args[i-1]\n                line = line_node.line\n                file = line_node.file\n                msg = join(arg.args, \", \")\n                throw(Meta.ParseError(\n                    replace(\"Error in line $line of $file: $msg\", \"\\\"\" => '`')\n                    )\n                )\n            end\n        end\n\n        const file_contents = read(stdin, String)\n        const ex = Meta.parseall(file_contents;\n            filename=\"/home/pbarletta/Downloads/tp-alineamientos-algoritmos/result.jl\"\n            )\n        throw_if_parse_err(ex)\n\n        function format_stdin()\n            print(format_text(file_contents; style = DefaultStyle(),indent = 4,margin = 92,normalize_line_endings = \"auto\"))\n        end\n\n        format_stdin()\n        "]
Exit with error code: 1
ERROR: UndefVarError: parseall not defined
Stacktrace:
 [1] getproperty(::Module, ::Symbol) at ./Base.jl:26
 [2] top-level scope at none:19
```
from the VSCode Output panel.

So it works on your machine?

**Comment by singularitti** [comment]
> So it works on your machine?
Yes.

It seems that you don't have the `Meta. parseall` function, which is strange, since it's shipped with Julia. Which version of Julia are you using?

**Comment by pgbarletta** [comment]
Yeap, that's it :(. I have 1.5, it seems Meta.parseall[ was added on 1.6](https://github.com/JuliaLang/julia/commit/f60aefe9dd3581f1088eb204ee2de1f36785db63), but the [changelog](https://github.com/JuliaLang/julia/blob/master/HISTORY.md) doesn't reflect it.

So, formatter requires 1.6. I'll guess I'll update.

**Comment by singularitti** [comment]
You're welcome!
