### ISSUE TITLE
ERROR: UndefVarError: parseall not defined

### ISSUE THREAD

**Issue by bestdan** [singularitti/vscode-julia-formatter#51]
Julia 1.6, using VSCode plugin. 
When I save (format-on-save is on), I get the following error: 

```
Running Julia with args: ["--compile=min","-e","using JuliaFormatter\n\n
...
ERROR: UndefVarError: parseall not defined
Stacktrace:
 [1] getproperty(::Module, ::Symbol) at ./Base.jl:26
 [2] top-level scope at none:19
```

Running `format_file()` directly in Julia works fine.

**Comment by acarta** [comment]
I am also experiencing this issue, albeit both when `format-on-save` is on and when I invoke the formatter manually.

**Comment by cpfiffer** [comment]
I believe this is because Julia 1.5 doesn't support `Meta.parseall`. So I would hazard a guess that the extension is asking 1.5 to format the code rather than Julia 1.6. How do we change which version of Julia the formatter dispatches to?

**Comment by singularitti** [comment]
Hey guys @bestdan @acarta @cpfiffer, the latest (1.5.0+) julia-vscode plugin already supports JuliaFormatter.jl as its default formatter. Could you try that?
