### ISSUE TITLE
Where is `.JuliaFormatter.toml` file located?

### ISSUE THREAD

**Issue by junglegobs** [singularitti/vscode-julia-formatter#54]
This VSCode extension appears to ignore the options I give it, so I was wondering how I could check where the `.JuliaFormatter.toml` file is.

**Comment by singularitti** [comment]
Hey guys @junglegobs, the latest (1.5.0+) julia-vscode plugin already supports JuliaFormatter.jl as its default formatter. Could you try that?

**Comment by junglegobs** [comment]
Hey @singularitti, I am on the latest version, [1.4.3](https://github.com/julia-vscode/julia-vscode) - how exactly do I get 1.5.0?

**Comment by singularitti** [comment]
> Hey @singularitti, I am on the latest version, [1.4.3](https://github.com/julia-vscode/julia-vscode) - how exactly do I get 1.5.0?

https://marketplace.visualstudio.com/items?itemName=julialang.language-julia-insider
