### ISSUE TITLE
Add option to specify environment

### ISSUE THREAD

**Issue by devmotion** [singularitti/vscode-julia-formatter#55]
Currently JuliaFormatter has to be installed in the global environment it seems. It would be convenient if one could specify a custom environment, similar to `environmentPath` in the julia-vscode extension. That would make it possible to install and update JuliaFormatter without interfering with other packages, e.g., by
```shell
julia --project=~/.julia/environments/juliaformatter -e 'using Pkg; Pkg.add("JuliaFormatter")'
```
and
```shell
julia --project=~/.julia/environments/juliaformatter -e 'using Pkg; Pkg.update()'
```

**Comment by singularitti** [comment]
Hey guys @devmotion, the [latest (1.5.0+) julia-vscode plugin](https://github.com/julia-vscode/julia-vscode/releases/tag/v1.5.0) already supports JuliaFormatter.jl as its default formatter. Could you try that?

**Comment by devmotion** [comment]
Oh that's great news, I was hoping for the integration but didn't expect it to happen so soon. I'll check it.
