### ISSUE TITLE
No spaces around .== and .&&

### ISSUE THREAD

**Issue by pascalschulthess** [singularitti/vscode-julia-formatter#56]
I have a large DataFrame `a` and when I filter this it get formatted as:
```
b = a[a.x.=="1".&&a.y.==5, :]
```
So, there are no spaces around `.==` or `.&&`. Is this intentional? Because this makes the code very unreadable.

**Comment by singularitti** [comment]
Hi @pascalschulthess, did you try the official [Julia extension](https://www.julia-vscode.org/)? They now use `JuliaFormatter.jl` by default (which is the formatter this extension uses). Does it solve your problem?

**Comment by pascalschulthess** [comment]
Yes, I have the official Julia extension installed. I've now removed `JuliaFormatter.jl` and tried it again. Still the same issue.
