### ISSUE TITLE
Maybe unpublish the extension?

### ISSUE THREAD

**Issue by davidanthoff** [singularitti/vscode-julia-formatter#57]
Would it make sense to fully unpublish the extension from the marketplace, as described [here](https://code.visualstudio.com/api/working-with-extensions/publishing-extension#unpublishing-extensions)? Or does it still provide some features that the main Julia extension doesn't have? I think at the moment there is no indication for users in the marketplace that they don't need this extension anymore.

**Comment by singularitti** [comment]
Sure, I don't know how to do that before!

**Comment by singularitti** [comment]
Done! @davidanthoff

**Comment by davidanthoff** [comment]
Thanks :)
