### ISSUE TITLE
Formatting is very slow

### ISSUE THREAD

**Issue by norru** [singularitti/vscode-julia-formatter#6]
Formatting is too slow to be usable at all.

I've tried to execute the spawned `julia` process with different `--compile` options. The default one (--compile=min) produces the worst results.

```
$ time /usr/local/bin/julia -e "using JuliaFormatter" -e "format(\"my/Code.jl\"; overwrite = true, indent = 4, margin = 120, always_for_in = true, whitespace_typedefs = false, whitespace_ops_in_indices = false)"

real	0m15.994s
user	0m14.666s
sys	0m0.285s
$ time /usr/local/bin/julia --compile=min -e "using JuliaFormatter" -e "format(\"my/Code.jl\"; overwrite = true, indent = 4, margin = 120, always_for_in = true, whitespace_typedefs = false, whitespace_ops_in_indices = false)"

real	1m31.356s
user	1m29.385s
sys	0m0.340s
$ time /usr/local/bin/julia --compile=all -e "using JuliaFormatter" -e "format(\"my/Code.jl\"; overwrite = true, indent = 4, margin = 120, always_for_in = true, whitespace_typedefs = false, whitespace_ops_in_indices = false)"

real	0m10.596s
user	0m10.864s
sys	0m0.432s
$ time /usr/local/bin/julia --compile=yes -e "using JuliaFormatter" -e "format(\"my/Code.jl\"; overwrite = true, indent = 4, margin = 120, always_for_in = true, whitespace_typedefs = false, whitespace_ops_in_indices = false)"

real	0m10.681s
user	0m10.945s
sys	0m0.439s
```

The other options are a bit better but still 10-15 seconds to interactively format a single source file is unacceptable.

In Atom only the first file takes long (time for the `julia` process to fire up) but every subsequent file is pretty much instant. This is probably due to Atom reusing the same `julia` process for multilple formatting operations.

Ideally we want `JuliaFormatter` to be executed by the Julia Language Server. The Language Server has its own formatter but it produces significantly inferior results.

**Comment by FelipeLema** [comment]
Hello, there

I've worked out a package to use [JuliaFormatter.jl](https://github.com/domluna/JuliaFormatter.jl) as backend to correctly code _while typing_:

https://codeberg.org/FelipeLema/julia-formatter.el

It runs a server in the background at startup, so all code formatting happens *without the need to JIT-recompile JuliaFormatter.jl*. You can re-use the server script to address this issue.

**Comment by rben01** [comment]
Here's the script I slapped together to keep an auto-formatting server running that formats on every save; just open a separate REPL and call this function with the path to your workspace as the first argument:

```Julia
using JuliaFormatter, FileWatching

function watch_and_format_dir(watched_dir::AbstractString, timeout_sec::Real=-1, debounce_time_sec::Real=1)
	while true
		file_changed, change_info = watch_folder(watched_dir, timeout_sec)
		if change_info.changed
			println(file_changed)
			format(joinpath(watched_dir, file_changed))
		end
		unwatch_folder(watched_dir)
		sleep(debounce_time_sec)
	end
end
```

Works fine if you only save one file at a time, and can easily be changed to operate on the entire directory each time a change is made (in case you frequently save several files at once) by replacing `format(joinpath(watched_dir, file_changed))` with `format(watched_dir)`. After the first pass (when I assume things are being compiled), formatting happens pretty much immediately for me.

**Comment by singularitti** [comment]
> Formatting is too slow to be usable at all.
> 
> I've tried to execute the spawned `julia` process with different `--compile` options. The default one (--compile=min) produces the worst results.
> 
> ```
> $ time /usr/local/bin/julia -e "using JuliaFormatter" -e "format(\"my/Code.jl\"; overwrite = true, indent = 4, margin = 120, always_for_in = true, whitespace_typedefs = false, whitespace_ops_in_indices = false)"
> 
> real	0m15.994s
> user	0m14.666s
> sys	0m0.285s
> $ time /usr/local/bin/julia --compile=min -e "using JuliaFormatter" -e "format(\"my/Code.jl\"; overwrite = true, indent = 4, margin = 120, always_for_in = true, whitespace_typedefs = false, whitespace_ops_in_indices = false)"
> 
> real	1m31.356s
> user	1m29.385s
> sys	0m0.340s
> $ time /usr/local/bin/julia --compile=all -e "using JuliaFormatter" -e "format(\"my/Code.jl\"; overwrite = true, indent = 4, margin = 120, always_for_in = true, whitespace_typedefs = false, whitespace_ops_in_indices = false)"
> 
> real	0m10.596s
> user	0m10.864s
> sys	0m0.432s
> $ time /usr/local/bin/julia --compile=yes -e "using JuliaFormatter" -e "format(\"my/Code.jl\"; overwrite = true, indent = 4, margin = 120, always_for_in = true, whitespace_typedefs = false, whitespace_ops_in_indices = false)"
> 
> real	0m10.681s
> user	0m10.945s
> sys	0m0.439s
> ```
> 
> The other options are a bit better but still 10-15 seconds to interactively format a single source file is unacceptable.
> 
> In Atom only the first file takes long (time for the `julia` process to fire up) but every subsequent file is pretty much instant. This is probably due to Atom reusing the same `julia` process for multilple formatting operations.
> 
> Ideally we want `JuliaFormatter` to be executed by the Julia Language Server. The Language Server has its own formatter but it produces significantly inferior results.

Hi @norru, can you try to build a `sysimage` to see if it is faster? We now support this feature:

> juliaFormatter.systemImagePath: The path to the sysimage to use when launching the Julia process that will format a file. If empty, no sysimage will be used. Read the PackageCompiler.jl documentation to learn why and how to create a sysimage. (Tl;dr a sysimage is a snapshot of the compiled functions in a Julia session, which can be reused to nearly eliminate the long compilation times Julia tends to suffer from. Using a sysimage can vastly reduce the time it takes to format files.)

**Comment by norru** [comment]
Hi, I have stopped using Julia a while ago. I'll keep you posted if I getto work on it again. I don't think a custom sysImage would have worked for me though.

**Comment by rben01** [comment]
@singularitti Unfortunately, while launching Julia with a `sysimage` (that has been saved with `JuliaFormatter`'s compilation state) is much faster than not using one, it's still not as fast as having a REPL monitor a file/folder for changes and call `format_file` -- launching Julia each time a file has to be formatted is slow. Do you know if it's possible to have the extension launch a background Julia shell and send formatting commands to it, then receive the updated file back and pass it to the VSCode extension so that it can be diffed and the hunks applied? I'm happy to work on this, just don't know where to start looking for docs.

**Comment by singularitti** [comment]
> Do you know if it's possible to have the extension launch a background Julia shell and send formatting commands to it, then receive the updated file back and pass it to the VSCode extension so that it can be diffed and the hunks applied?

Technically, it is possible. That's what they are doing in [julia-vscode](https://github.com/julia-vscode/LanguageServer.jl/pull/759). If you have time, maybe contribute to them? Eventually after this feature is merged, I will deprecate this extension.

**Comment by singularitti** [comment]
Hey guys @norru @FelipeLema @rben01 , the latest (1.5.0+) julia-vscode plugin already supports JuliaFormatter.jl as its default formatter. Could you try that?

**Comment by rben01** [comment]
> Hey guys @norru @FelipeLema @rben01 , the latest (1.5.0+) julia-vscode plugin already supports JuliaFormatter.jl as its default formatter. Could you try that?

Yes, much faster. Does that spell the end of this extension 😢?

**Comment by singularitti** [comment]
I guess so. I may fix a few bugs if I have time. But the official Julia plugin is superior to this one in every dimension. I can hardly think of a reason to keep maintaining this plugin. But I am so grateful for your help & feedback!
