### ISSUE TITLE
Cannot save src file

### ISSUE THREAD

**Issue by bearberror** [singularitti/vscode-julia-formatter#60]
ERROR: MethodError: no method matching format_text(::String; style=DefaultStyle(nothing), indent=4, margin=92, normalize_line_endings="auto")

**Comment by singularitti** [comment]
Hi @bearberror, this extension has been deprecated. Please use the official vscode extension [`julia-vscode`](https://github.com/julia-vscode/julia-vscode), which covers the whole functionalities of this extension!
