### ISSUE TITLE
Selecting "compile=all" in VSC option still executes the child Julia with "compile=min"

### ISSUE THREAD

**Issue by norru** [singularitti/vscode-julia-formatter#7]
Steps to reproduce:

- VSC `Ctrl+,` to open Settings
- Go to "Julia Formatter: Compile
Control the compilation level of Julia. Available values are 'min' or 'all'."
- select "all"
- close settigs
- open a Julia file
- right click/format document with.../julia formatter
- check the system's process list with `ps` or similar tools

Result:
Julia formatter is invoked with `--compile=min` option

Expected result:
Julia formatter is invoked with `--compile=all` option

**Comment by singularitti** [comment]
Hi @norru, could you try the latest build. Is this problem still happening? I am working fine on macOS.
