### ISSUE TITLE
Command failed on windows

### ISSUE THREAD

**Issue by rockliu601** [singularitti/vscode-julia-formatter#9]
> Command failed: julia --compile=min -e 'using JuliaFormatter' -e 'format("C:\path\to\some\file.jl"; overwrite = true, indent = 4, margin = 92, always_for_in = true, whitespace_typedefs = false, whitespace_ops_in_indices = false)'
ERROR: syntax: incomplete: invalid character literal
Stacktrace:
[1] top-level scope at none:0

On windows, backslash "\\" in file path should be double backslashes "\\\\".

**Comment by singularitti** [comment]
Could you try whether 0.0.6 solves your problem since we have #10? @rockliu601

**Comment by rockliu601** [comment]
I haven't used vscode in recent days. I tried 0.1.0 today and it works well. Thank you! @singularitti
